export const GET_DETAIL_MOVIES_REQUEST = '@@detailmovies/GET_DETAIL_MOVIES_REQUEST';
export const GET_DETAIL_MOVIES_SUCCESS = '@@detailmovies/GET_DETAIL_MOVIES_SUCCESS';
export const GET_DETAIL_MOVIES_FAIL = '@@detailmovies/GET_DETAIL_MOVIES_FAIL';
