export const GET_HE_THONG_RAP_HOMEMENU_REQUEST = '@@HomeMenu/GET_HE_THONG_RAP_HOMEMENU_REQUEST';
export const GET_HE_THONG_RAP_HOMEMENU_SUCCESS = '@@HomeMenu/GET_HE_THONG_RAP_HOMEMENU_SUCCESS';
export const GET_HE_THONG_RAP_HOMEMENU_FAIL = '@@HomeMenu/GET_HE_THONG_RAP_HOMEMENU_FAIL';