export const GET_THONG_TIN_NGUOI_DUNG_REQUEST = '@@checkout/GET_THONG_TIN_NGUOI_DUNG_REQUEST';
export const GET_THONG_TIN_NGUOI_DUNG_SUCCESS = '@@checkout/GET_THONG_TIN_NGUOI_DUNG_SUCCESS';
export const GET_THONG_TIN_NGUOI_DUNG_FAIL = '@@checkout/GET_THONG_TIN_NGUOI_DUNG_FAIL';