export const DANH_SACH_BANNER_REQUEST = '@@Carosel/DANH_SACH_BANNER_REQUEST';
export const DANH_SACH_BANNER_FAIL = '@@Carosel/DANH_SACH_BANNER_FAIL';
export const DANH_SACH_BANNER_SUCCESS = '@@Carosel/DANH_SACH_BANNER_SUCCESS';